name: Daily README Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest  # Use Ubuntu runner (you can also use windows-latest if needed)

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update README
      run: |
        echo "Last updated: $(date)" > README.md
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
        git add README.md
        git commit -m "Daily update" || echo "No changes to commit"
        git push || echo "Failed to push changes"
