name: Metrics

on:
  schedule: [{cron: "0 6 * * 1"}]  # Runs every Monday at 6:00 am UTC
  workflow_dispatch:  # Allows manual triggering
  push:  # Triggers on push

jobs:
  github-metrics:
    runs-on: ubuntu-latest  # Changed from windows-latest
    environment: 
      name: APIL_JUNG_THAPA
    permissions:
      contents: write
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: assets/general.svg
          token: ${{ secrets.APIL_JUNG_THAPA }}  # Your secret
          user: Apiljungthapa
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kathmandu
